### PR TITLE
Converted $cssRules to a local variable returned by processCSS

### PR DESCRIPTION
**Pull request by jproffitt3ge**
See: https://github.com/tijsverkoyen/CssToInlineStyles/issues/105

### CODE REVIEW

**Comment by Hikariii** [comment]
+1, seeing the same leaking behaviour.
Css and Html can be reset, but the stored rules cannot be cleared.

**Comment by stof** [comment]
:+1:

**Comment by HarmenM** [comment]
+1

It would really help to have this pull request merged.

**Comment by tijsverkoyen** [comment]
The whole behaviour has been changed in #111

**Comment by stof** [comment]
@tijsverkoyen it would be great to make a new 1.x release with this fix included

**Pull request merged**
