### PR TITLE
Support Symfony 2 + 3

### PR DESCRIPTION
**Pull request by barryvdh**
See #107 

Moves XPath generation to seperate class, detect Symfony 2 or 3.

### CODE REVIEW

**Comment by stof** [comment]
I would rather create a private method receiving the selector as argument and returning the XPath

**Comment by tijsverkoyen** [comment]
See #111

**Comment by stof** [comment]
@tijsverkoyen given that Symfony 3 is released soon, it would be great to have such fix in 1.x already to make it compatible with Symfony 3.

**Comment by stof** [comment]
@tijsverkoyen can you reconsider this as Symfony 3 is stable now ?

**Pull request merged**
